---
apiVersion: v1
kind: Service
metadata:
  name: goserver-svc
  labels:
    app: goserver
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
  - name: goserver-http
    port: 80
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
      - name: goserver
        image: fkmatsuda/server:0.0.14
        startupProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 1
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 3
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 1
          successThreshold: 1
          initialDelaySeconds: 30
        envFrom:
        - configMapRef:
            name: server-env
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        ports:
          - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: goserver-hpa
  labels:
    app: goserver
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: goserver
  minReplicas: 3
  maxReplicas: 6
  metrics:
  targetCPUUtilizationPercentage: 75
      