apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    app: goserver
spec:
  containers:
  - name: goserver
    image: fkmatsuda/server:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
