apiVersion: v1
kind: Service
metadata:
  name: goserver-svc
  labels:
    app: goserver
spec:
  selector:
    app: goserver
  type: ClusterIP
  ports:
  - name: goserver-http
    port: 80
    protocol: TCP